before_script:
    - source /etc/profile

stages:
    - build

run-build:
    stage: build
    script:
        - apt-get install -y bash-completion devscripts
        - debuild -us -uc -b
        - mkdir build
        - mv ../*.deb build/

    artifacts:
        paths:
            - build/*
